"""Add account_balance to bank

Revision ID: a65877a5ab64
Revises: 
Create Date: 2025-06-03 16:46:44.133188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65877a5ab64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.drop_column('account_balance')

    # ### end Alembic commands ###
